### ISSUE TITLE
Update code to allow the GPS to work at altitude

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#102]
Remove altitude limitations we currently have with existing code.

@snarfattack and @ssamjung2 I think had an email trail with how to solve this. I tentatively assign them on this. We will discuss when we huddle as a core team as well.

**Comment by tdeknecht** [comment]
Does this apply to both the `c` and `python` projects?

**Comment by pankonen** [comment]
Honestly I'm not sure. I'm not sure I can easily identify which data files are Pico vs Arduino in the [folder](https://github.com/StateFarm-STEM/hablogger/tree/main/telemetry-analysis/flights). I THINK it was Android only.

I'll pop a story to update post flight procedures / tasks one being to upload the data to Github and identify the files a little better. I'll also make sure we are formatting the data the same and at the same time intervals.

**Comment by snarfattack** [comment]
I copied code from the Arduino based APRS trackers that were working as expected at high altitude.
The GPS modules with GoouuuTech branding on them do not work when placed into high altitude mode. We get no lat/lon coordinates back from the module.
I purchased the [HiLetgo NEO-7M GPS](https://www.amazon.com/dp/B07X5GVW6Q) module instead, and the code works as expected at low altitude during testing. These modules have ublox branded gps chips.

Since we expect that classes will still use the old modules for now and we want them to still get locks and gps data at low altitude, I will upload the high altitude code to fly in a separate code file.
