### ISSUE TITLE
IDE / development environment decision

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#5]
While poking around the other day I found there are what looks like two options for working with the Pico.

[Thonny](https://thonny.org/)

- More like a default Python SDK from what I can tell?

[Circuit Python](https://circuitpython.org/)

- Looks to ease the introduction to Python

What are everyones thoughts?

**Comment by tdeknecht** [comment]
These are two different things and can be treated as separate decisions.

Thonny is the IDE or code executor we'd be using to interface with the Pico. You can choose within Thonny CircuitPython as an interpreter the same way you can choose MicroPython.

For the interpreter we could go the route of MicroPython or CircuitPython. Being inexperienced at this point, my vote is for MicroPython because we've not yet hit any limitations with the packages it comes with. If we hit scenarios where MicroPython isn't cutting it and we don't want to compile our own interpreter, we could look closer at CircuitPython.

All that said, I vote Thonny using MicroPython to start.

**Comment by pankonen** [comment]
For the time being lets move forward with Thonny
