### ISSUE TITLE
Lesson 6 Additional detail needed

### ISSUE THREAD

**Issue by snarfattack** [StateFarm-STEM/hablogger#67]
No need to move the pico over in the breadboard! 

Link 5v from the pico pin 1 to the +(Red) bus on the breadboard. Link GND from the pico pin3 to the -(Blue). Then each sensor board, connect the VCC to the +(Red) bus and the GND to the -(Blue) bus.

We need to enhance the instructions to include a link to the new main.py.

Main.py includes a reference to SSD1306 for the OLED, which hasn't been covered yet, and isn't actually used in the main.py.

**Comment by tdeknecht** [comment]
@snarfattack I removed the SSD1306 import (it was left over from when I had the OLED in this lesson). I also removed the LED code to keep things simpler.

I follow what you are saying about using the breadboard. I did not have the pinout added in the diagram for the breadboard, assuming at this point the students would be able to infer from the wiring diagram the best way to use the breadboard for all the modules. In a way, leaving somewhat of a challenge for them to figure out that bit of the wiring. I did add a hint to using the breadboard based on how I have it wired and because of your suggestion.

Can you expand on what you mean by the "new main.py?"

You can see my current changes in [this branch](https://github.com/StateFarm-STEM/hablogger/tree/issue-67). Feel free to add comments in the code.

**Comment by snarfattack** [comment]
In class, couple of our teams started by attempting to remove the pico from the breadboard to shift it over to get more holes to the side of the 5v and gnd pins. Since lessons 3-5 didn't re-inforce the concept of how to use the power bus, they forgot it. I had to re-teach it to our teams. Worried that people might damage picos if we leave it up to them and they decide to move picos.

I see it includes a link to the main.py now, but the path is wrong and returns 404 as there is a duplicate lesson 6 in the path.

Thanks!

**Comment by tdeknecht** [comment]
@snarfattack I see what you mean about not wanting to remove the pico. If I get time between now and Friday I'll see about including a breadboard in the pinout diagram to use the power buses on the sides.

I updated the link, too. Nice catch!

**Comment by tdeknecht** [comment]
@snarfattack I pulled in @TrevBart fixes and pushed the branch. I'm going to merge it. This should close out this issue.

@TrevBart , I removed the `time.sleep(1)` you included. I've seen that mess with the GPS data collection before. I don't want to inadvertently add an issue for the students.

**Comment by tdeknecht** [comment]
Issues fixed in https://github.com/StateFarm-STEM/hablogger/pull/71
